import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { Inter as FontSans } from "next/font/google"
import {rubik} from '@/lib/fonts'
import { cn } from "@/lib/utils"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { useTranslations } from 'next-intl';
import { Button } from '@/components/ui/button';
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {

  const font = locale === 'ar' ? rubik.className :  fontSans.variable;
  const documentDirection = locale === 'ar' ? "rtl" :  "ltr";

  const Navigation = useTranslations('navigation');
  const navLinks = [
    [Navigation('home'), 'home'],
    [Navigation('services'), 'services'],
    [Navigation('pr'), 'products'],
    [Navigation('about'), 'about'],
    [Navigation('contact'), 'contact']
  ];

  return (
    <html lang={locale} dir={documentDirection}>
      <body 
      className={cn(
        "min-h-screen w-full font-sans antialiased",
        font )}>
        <Header locale={locale} navLinks= {navLinks}  />
          <div className='flex-grow'>{children}</div>
        <Footer locale={locale} navLinks= {navLinks} />
      </body>
    </html>
  );
}
